name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync code to EC2 production folder
        run: |
          rsync -av --delete ${{ github.workspace }}/ /home/ubuntu/CS-490-GP-Backend/
          rsync -av --delete --exclude='.env' ${{ github.workspace }}/ /home/ubuntu/CS-490-GP-Backend/

      - name: Install Node dependencies
        run: |
          cd /home/ubuntu/CS-490-GP-Backend
          npm install

      - name: Restart PM2 (stygo-backend)
        run: |
          pm2 stop stygo-backend || true
          pm2 start /home/ubuntu/CS-490-GP-Backend/app.js --name stygo-backend
          pm2 save
