name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # 1. CHECKOUT REPO
      # -----------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # -----------------------------
      # 2. CONFIGURE AWS CREDENTIALS
      # -----------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # -----------------------------
      # 3. START EC2 INSTANCE.
      # -----------------------------
      - name: Start EC2 instance
        run: |
          rsync -av --delete ${{ github.workspace }}/ /home/ubuntu/CS-490-GP-Backend/
          rsync -av --delete --exclude='.env' ${{ github.workspace }}/ /home/ubuntu/CS-490-GP-Backend/

      - name: Install Node dependencies
        run: |
          cd /home/ubuntu/CS-490-GP-Backend
          npm install

      - name: Restart PM2 (stygo-backend)
        run: |
          pm2 stop stygo-backend || true
          pm2 start /home/ubuntu/CS-490-GP-Backend/app.js --name stygo-backend
          pm2 save
